# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
          
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/floodme:latest
  
  deploy:
    if: ${{ false }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: deploy
        uses: azure/aci-deploy@v1
        
        with:
          resource-group: floodaware
          location: 'australiaeast'
          name: floodaware-api
          dns-name-label: floodaware-api
          image: natohutch/floodme
          cpu: 0.5
          memory: 0.5
          ip-address: public
          ports: 5000
          secure-environment-variables: dbhost=${{ secrets.DBHOST }} dbpword=${{ secrets.DBPWORD }}
          
            
    
    
